### ISSUE TITLE
Collaboration Infrastructure - Wiki

### ISSUE THREAD

**Issue by MuradPats** [MuradPats/softproj#15]

**Comment by MuradPats** [comment]
@huberflores hi, you should be able to access everythinig "in read only" mode. We haven't commited any code yet, until then could you give us some feedback on what should we change/do better to not lose any points for the first iteration. I'm especially interested in linking requirements to the issues. Did I do it right

**Comment by huberflores** [comment]
I am preparing your feedback for the first iteration. One main comment of your project right now is the home page.  There is no description about what are you planning to build, e.g., mobile app, Web application, etc. This page should answer questions such as, what is the project about? goals? objectives? etc.  Limitations can be set in order to define specifically the purpose of the application, e.g., it can be used just by developers, it can be used by any person, etc. It could be possible to envision a use case with a few sentences, or even you could build a flow diagram. You could also check this wiki in order to get an idea about the deliverable of this iteration (https://github.com/TaaviGilden/Prawesome/wiki). I will provide more specific details of your iteration soon.

**Comment by MuradPats** [comment]
[wiki](https://github.com/MuradPats/softproj/wiki) should be done now
